Internal Server Error: /stockPrediction/BABY
Traceback (most recent call last):
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/views.py", line 407, in dispatch
    response = self.handle_exception(exc)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/views.py", line 404, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/tyan/project/StockPredict/BACK/predictCenter/views.py", line 80, in get
    cacheP = stock.prediction.all()[0]
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/django/db/models/query.py", line 177, in __getitem__
    return list(qs)[0]
IndexError: list index out of range
Internal Server Error: /stockPrediction/BABY
Traceback (most recent call last):
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/views.py", line 407, in dispatch
    response = self.handle_exception(exc)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/views.py", line 404, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/tyan/project/StockPredict/BACK/predictCenter/views.py", line 95, in get
    return Response(serializer.data, status=status.HTTP_201_CREATED)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/serializers.py", line 463, in data
    ret = super(Serializer, self).data
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/serializers.py", line 212, in data
    self._data = self.to_representation(self.instance)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/serializers.py", line 432, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/fields.py", line 701, in to_representation
    return float(value)
ValueError: invalid literal for float(): 2001-07-31
Internal Server Error: /stockPrediction/BABY
Traceback (most recent call last):
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/views.py", line 407, in dispatch
    response = self.handle_exception(exc)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/views.py", line 404, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/tyan/project/StockPredict/BACK/predictCenter/views.py", line 95, in get
    print serializer.data
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/serializers.py", line 463, in data
    ret = super(Serializer, self).data
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/serializers.py", line 212, in data
    self._data = self.to_representation(self.instance)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/serializers.py", line 432, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/fields.py", line 701, in to_representation
    return float(value)
ValueError: invalid literal for float(): 2001-07-31
Internal Server Error: /stockPrediction/BABY
Traceback (most recent call last):
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/views.py", line 407, in dispatch
    response = self.handle_exception(exc)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/views.py", line 404, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/tyan/project/StockPredict/BACK/predictCenter/views.py", line 96, in get
    return Response(serializer.data, status=status.HTTP_201_CREATED)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/serializers.py", line 463, in data
    ret = super(Serializer, self).data
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/serializers.py", line 212, in data
    self._data = self.to_representation(self.instance)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/serializers.py", line 432, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/fields.py", line 701, in to_representation
    return float(value)
ValueError: invalid literal for float(): 2001-07-31
Internal Server Error: /stockPrediction/BABY
Traceback (most recent call last):
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/views.py", line 407, in dispatch
    response = self.handle_exception(exc)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/views.py", line 404, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/tyan/project/StockPredict/BACK/predictCenter/views.py", line 96, in get
    return Response(serializer.data, status=status.HTTP_201_CREATED)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/serializers.py", line 463, in data
    ret = super(Serializer, self).data
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/serializers.py", line 212, in data
    self._data = self.to_representation(self.instance)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/serializers.py", line 432, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/fields.py", line 701, in to_representation
    return float(value)
ValueError: invalid literal for float(): 2001-07-31
Not Found: /
Not Found: /favicon.ico
Not Found: /favicon.ico
Internal Server Error: /userStock/
Traceback (most recent call last):
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/views.py", line 407, in dispatch
    response = self.handle_exception(exc)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/views.py", line 404, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/tyan/project/StockPredict/BACK/predictCenter/views.py", line 47, in get
    userStocks = UserStock.objects.filter(user=request.user)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/django/db/models/query.py", line 691, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/django/db/models/query.py", line 709, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1331, in add_q
    clause, require_inner = self._add_q(where_part, self.used_aliases)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1358, in _add_q
    current_negated=current_negated, connector=connector)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1225, in build_filter
    lookups, value)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/django/db/models/fields/related.py", line 1558, in get_lookup_constraint
    lookup_class(Col(alias, target, source), val), AND)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/django/db/models/lookups.py", line 82, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/django/db/models/lookups.py", line 85, in get_prep_lookup
    return self.lhs.output_field.get_prep_lookup(self.lookup_name, self.rhs)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 646, in get_prep_lookup
    return self.get_prep_value(value)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 915, in get_prep_value
    return int(value)
TypeError: int() argument must be a string or a number, not 'AnonymousUser'
Internal Server Error: /userStock/
Traceback (most recent call last):
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/views.py", line 407, in dispatch
    response = self.handle_exception(exc)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/views.py", line 404, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/tyan/project/StockPredict/BACK/predictCenter/views.py", line 46, in get
    userStocks = UserStock.objects.filter(user=request.user)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/django/db/models/query.py", line 691, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/django/db/models/query.py", line 709, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1331, in add_q
    clause, require_inner = self._add_q(where_part, self.used_aliases)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1358, in _add_q
    current_negated=current_negated, connector=connector)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1225, in build_filter
    lookups, value)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/django/db/models/fields/related.py", line 1558, in get_lookup_constraint
    lookup_class(Col(alias, target, source), val), AND)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/django/db/models/lookups.py", line 82, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/django/db/models/lookups.py", line 85, in get_prep_lookup
    return self.lhs.output_field.get_prep_lookup(self.lookup_name, self.rhs)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 646, in get_prep_lookup
    return self.get_prep_value(value)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 915, in get_prep_value
    return int(value)
TypeError: int() argument must be a string or a number, not 'AnonymousUser'
Internal Server Error: /userStock/1
Traceback (most recent call last):
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/views.py", line 407, in dispatch
    response = self.handle_exception(exc)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/views.py", line 404, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/generics.py", line 354, in get
    return self.retrieve(request, *args, **kwargs)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/mixins.py", line 54, in retrieve
    instance = self.get_object()
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/generics.py", line 229, in get_object
    queryset = self.filter_queryset(self.get_queryset())
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/generics.py", line 212, in get_queryset
    % self.__class__.__name__
AssertionError: 'UserStockDetail' should either include a `queryset` attribute, or override the `get_queryset()` method.
Internal Server Error: /userStock/1
Traceback (most recent call last):
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/views.py", line 407, in dispatch
    response = self.handle_exception(exc)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/views.py", line 404, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/generics.py", line 354, in get
    return self.retrieve(request, *args, **kwargs)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/mixins.py", line 55, in retrieve
    serializer = self.get_serializer(instance)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/generics.py", line 87, in get_serializer
    serializer_class = self.get_serializer_class()
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/generics.py", line 189, in get_serializer_class
    % self.__class__.__name__
AssertionError: 'UserStockDetail' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
Internal Server Error: /userStock/1
Traceback (most recent call last):
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/views.py", line 407, in dispatch
    response = self.handle_exception(exc)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/views.py", line 404, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/generics.py", line 354, in get
    return self.retrieve(request, *args, **kwargs)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/mixins.py", line 55, in retrieve
    serializer = self.get_serializer(instance)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/generics.py", line 87, in get_serializer
    serializer_class = self.get_serializer_class()
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/generics.py", line 189, in get_serializer_class
    % self.__class__.__name__
AssertionError: 'UserStockDetail' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
Internal Server Error: /userStock/1
Traceback (most recent call last):
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/views.py", line 407, in dispatch
    response = self.handle_exception(exc)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/views.py", line 404, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/generics.py", line 354, in get
    return self.retrieve(request, *args, **kwargs)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/mixins.py", line 55, in retrieve
    serializer = self.get_serializer(instance)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/generics.py", line 87, in get_serializer
    serializer_class = self.get_serializer_class()
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/generics.py", line 189, in get_serializer_class
    % self.__class__.__name__
AssertionError: 'UserStockDetail' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
Not Found: /spstats
Not Found: /spstat
Not Found: /ststat/1
Not Found: /spstat/1
Not Found: /spstat/1
Not Found: /
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /web
Not Found: /accounts/profile/
Not Found: /userInfo/undefined/
Internal Server Error: /userInfo/1/
Traceback (most recent call last):
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/views.py", line 407, in dispatch
    response = self.handle_exception(exc)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/views.py", line 404, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/generics.py", line 278, in get
    return self.retrieve(request, *args, **kwargs)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/mixins.py", line 54, in retrieve
    instance = self.get_object()
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/generics.py", line 245, in get_object
    self.check_object_permissions(self.request, obj)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/views.py", line 291, in check_object_permissions
    if not permission.has_object_permission(request, self, obj):
  File "/home/tyan/project/StockPredict/BACK/userSys/permissions.py", line 20, in has_object_permission
    return obj.user == request.user
AttributeError: 'User' object has no attribute 'user'
Internal Server Error: /userInfo/1/
Traceback (most recent call last):
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/views.py", line 407, in dispatch
    response = self.handle_exception(exc)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/views.py", line 404, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/generics.py", line 278, in get
    return self.retrieve(request, *args, **kwargs)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/mixins.py", line 54, in retrieve
    instance = self.get_object()
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/generics.py", line 245, in get_object
    self.check_object_permissions(self.request, obj)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/views.py", line 291, in check_object_permissions
    if not permission.has_object_permission(request, self, obj):
  File "/home/tyan/project/StockPredict/BACK/userSys/permissions.py", line 20, in has_object_permission
    return obj.user == request.user
AttributeError: 'User' object has no attribute 'user'
Internal Server Error: /userInfo/1/
Traceback (most recent call last):
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/views.py", line 407, in dispatch
    response = self.handle_exception(exc)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/views.py", line 404, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/generics.py", line 278, in get
    return self.retrieve(request, *args, **kwargs)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/mixins.py", line 54, in retrieve
    instance = self.get_object()
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/generics.py", line 245, in get_object
    self.check_object_permissions(self.request, obj)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/views.py", line 291, in check_object_permissions
    if not permission.has_object_permission(request, self, obj):
  File "/home/tyan/project/StockPredict/BACK/userSys/permissions.py", line 20, in has_object_permission
    return obj.user == request.user
AttributeError: 'User' object has no attribute 'user'
Not Found: /bower_components/bootstrap/dist/css/bootstrap.css
Not Found: /bower_components/angular/angular.js
Not Found: /bower_components/bootstrap/dist/js/bootstrap.js
Not Found: /bower_components/jquery/dist/jquery.js
Not Found: /bower_components/angular-cookies/angular-cookies.js
Not Found: /bower_components/angular-resource/angular-resource.js
Not Found: /bower_components/angular-route/angular-route.js
Not Found: /bower_components/angular-sanitize/angular-sanitize.js
Not Found: /bower_components/angular/angular.js
Not Found: /bower_components/bootstrap/dist/js/bootstrap.js
Not Found: /bower_components/angular-cookies/angular-cookies.js
Not Found: /bower_components/angular-resource/angular-resource.js
Not Found: /bower_components/angular-route/angular-route.js
Not Found: /bower_components/angular-sanitize/angular-sanitize.js
Not Found: /favicon.ico
Not Found: /bower_components/bootstrap/dist/css/bootstrap.css
Not Found: /bower_components/jquery/dist/jquery.js
Not Found: /bower_components/angular/angular.js
Not Found: /bower_components/bootstrap/dist/js/bootstrap.js
Not Found: /bower_components/angular-cookies/angular-cookies.js
Not Found: /bower_components/angular-resource/angular-resource.js
Not Found: /bower_components/angular-route/angular-route.js
Not Found: /bower_components/angular-sanitize/angular-sanitize.js
Not Found: /bower_components/angular/angular.js
Not Found: /bower_components/bootstrap/dist/js/bootstrap.js
Not Found: /bower_components/angular-cookies/angular-cookies.js
Not Found: /bower_components/angular-resource/angular-resource.js
Not Found: /bower_components/angular-route/angular-route.js
Not Found: /bower_components/angular-sanitize/angular-sanitize.js
Not Found: /bower_components/bootstrap/dist/css/bootstrap.css
Not Found: /bower_components/jquery/dist/jquery.js
Not Found: /bower_components/angular/angular.js
Not Found: /bower_components/angular-cookies/angular-cookies.js
Not Found: /bower_components/bootstrap/dist/js/bootstrap.js
Not Found: /bower_components/angular-resource/angular-resource.js
Not Found: /bower_components/angular-route/angular-route.js
Not Found: /bower_components/angular-sanitize/angular-sanitize.js
Not Found: /bower_components/angular/angular.js
Not Found: /bower_components/bootstrap/dist/js/bootstrap.js
Not Found: /bower_components/angular-cookies/angular-cookies.js
Not Found: /bower_components/angular-resource/angular-resource.js
Not Found: /bower_components/angular-route/angular-route.js
Not Found: /bower_components/angular-sanitize/angular-sanitize.js
Internal Server Error: /userInfo/1/
Traceback (most recent call last):
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/views.py", line 407, in dispatch
    response = self.handle_exception(exc)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/views.py", line 404, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/generics.py", line 278, in get
    return self.retrieve(request, *args, **kwargs)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/mixins.py", line 54, in retrieve
    instance = self.get_object()
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/generics.py", line 245, in get_object
    self.check_object_permissions(self.request, obj)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/views.py", line 291, in check_object_permissions
    if not permission.has_object_permission(request, self, obj):
  File "/home/tyan/project/StockPredict/BACK/userSys/permissions.py", line 20, in has_object_permission
    return obj.user == request.user
AttributeError: 'User' object has no attribute 'user'
Internal Server Error: /userInfo/1/
Traceback (most recent call last):
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/views.py", line 407, in dispatch
    response = self.handle_exception(exc)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/views.py", line 404, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/generics.py", line 278, in get
    return self.retrieve(request, *args, **kwargs)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/mixins.py", line 54, in retrieve
    instance = self.get_object()
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/generics.py", line 245, in get_object
    self.check_object_permissions(self.request, obj)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/views.py", line 291, in check_object_permissions
    if not permission.has_object_permission(request, self, obj):
  File "/home/tyan/project/StockPredict/BACK/userSys/permissions.py", line 20, in has_object_permission
    return obj.user == request.user
AttributeError: 'User' object has no attribute 'user'
Not Found: /userInfo
Internal Server Error: /userInfo/1/
Traceback (most recent call last):
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/views.py", line 407, in dispatch
    response = self.handle_exception(exc)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/views.py", line 404, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/generics.py", line 278, in get
    return self.retrieve(request, *args, **kwargs)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/mixins.py", line 54, in retrieve
    instance = self.get_object()
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/generics.py", line 245, in get_object
    self.check_object_permissions(self.request, obj)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/views.py", line 291, in check_object_permissions
    if not permission.has_object_permission(request, self, obj):
  File "/home/tyan/project/StockPredict/BACK/userSys/permissions.py", line 20, in has_object_permission
    return obj.user == request.user
AttributeError: 'User' object has no attribute 'user'
Internal Server Error: /userInfo/
Traceback (most recent call last):
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/views.py", line 407, in dispatch
    response = self.handle_exception(exc)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/views.py", line 404, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/generics.py", line 278, in get
    return self.retrieve(request, *args, **kwargs)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/mixins.py", line 54, in retrieve
    instance = self.get_object()
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/generics.py", line 238, in get_object
    (self.__class__.__name__, lookup_url_kwarg)
AssertionError: Expected view UserInfoDetail to be called with a URL keyword argument named "pk". Fix your URL conf, or set the `.lookup_field` attribute on the view correctly.
Internal Server Error: /userInfo/
Traceback (most recent call last):
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/django/core/handlers/base.py", line 98, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 343, in resolve
    for pattern in self.url_patterns:
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 372, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 366, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/tyan/project/StockPredict/BACK/stockPredict/urls.py", line 36, in <module>
    url(r'^userInfo/$', USviews.UserInfoSerializer.as_view()),
AttributeError: type object 'UserInfoSerializer' has no attribute 'as_view'
Internal Server Error: /userInfo/
Traceback (most recent call last):
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/views.py", line 407, in dispatch
    response = self.handle_exception(exc)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/views.py", line 404, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/tyan/project/StockPredict/BACK/userSys/views.py", line 26, in get
    return Response(serializer.data)
NameError: global name 'serializer' is not defined
Internal Server Error: /userInfo/
Traceback (most recent call last):
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/views.py", line 407, in dispatch
    response = self.handle_exception(exc)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/views.py", line 404, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/tyan/project/StockPredict/BACK/userSys/views.py", line 26, in get
    return Response(serializer.data)
NameError: global name 'serializer' is not defined
Internal Server Error: /userInfo/
Traceback (most recent call last):
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/views.py", line 407, in dispatch
    response = self.handle_exception(exc)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/views.py", line 404, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/tyan/project/StockPredict/BACK/userSys/views.py", line 26, in get
    return Response(serializer.data)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/serializers.py", line 463, in data
    ret = super(Serializer, self).data
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/serializers.py", line 212, in data
    self._data = self.to_representation(self.instance)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/serializers.py", line 423, in to_representation
    attribute = field.get_attribute(instance)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/fields.py", line 306, in get_attribute
    raise type(exc)(msg)
AttributeError: Got AttributeError when attempting to get a value for field `user` on serializer `UserInfoSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `User` instance.
Original exception text was: 'User' object has no attribute 'user'.
Internal Server Error: /userInfo/
Traceback (most recent call last):
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/views.py", line 407, in dispatch
    response = self.handle_exception(exc)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/views.py", line 404, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/tyan/project/StockPredict/BACK/userSys/views.py", line 28, in get
    return Response(serializer.data)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/serializers.py", line 463, in data
    ret = super(Serializer, self).data
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/serializers.py", line 212, in data
    self._data = self.to_representation(self.instance)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/serializers.py", line 423, in to_representation
    attribute = field.get_attribute(instance)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/fields.py", line 306, in get_attribute
    raise type(exc)(msg)
AttributeError: Got AttributeError when attempting to get a value for field `user` on serializer `UserInfoSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `User` instance.
Original exception text was: 'User' object has no attribute 'user'.
Internal Server Error: /userInfo/
Traceback (most recent call last):
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/views.py", line 407, in dispatch
    response = self.handle_exception(exc)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/views.py", line 404, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/tyan/project/StockPredict/BACK/userSys/views.py", line 28, in get
    return Response(serializer.data)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/serializers.py", line 463, in data
    ret = super(Serializer, self).data
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/serializers.py", line 212, in data
    self._data = self.to_representation(self.instance)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/serializers.py", line 423, in to_representation
    attribute = field.get_attribute(instance)
  File "/home/tyan/project/stENv/lib/python2.7/site-packages/rest_framework/fields.py", line 306, in get_attribute
    raise type(exc)(msg)
AttributeError: Got AttributeError when attempting to get a value for field `user` on serializer `UserInfoSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `User` instance.
Original exception text was: 'User' object has no attribute 'user'.
Not Found: /stockPrediction/BABA/
Not Found: /stockPrediction/undefined/
Not Found: /stockPrediction/BABA/
Not Found: /stockPrediction/BABA/
Not Found: /stockPrediction/BABA/
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /accounts/profile/
Not Found: /favicon.ico
Not Found: /favicon.ico
